---
kind: pipeline
type: kubernetes
name: default

clone:
  disable: true

steps:
- name: clone
  image: alpine/git
  commands:
  - git clone https://github.com/carpenike/helm-charts .
  - git checkout gh-pages
  
- name: build
  image: dtzar/helm-kubectl:2.16.1
  commands:
  - helm init -c
  - helm repo index --url https://charts.blazure.com ./

- name: push_gh-pages
  image: appleboy/drone-git-push
  settings:
    remote: git@github.com:carpenike/helm-charts.git
    # remote_name: origin
    branch: gh-pages
    local_branch: gh-pages
    commit: true
    force: true
    author_name: "[Automated] Drone.IO"
    author_email: "drone@holthome.net"
    path: helm-charts
    ssh_key:
      from_secret: SSH_KEY